[metadata]
creation_date = "2025/03/24"
integration = []
maturity = "development"
updated_date = "2025/03/24"

[rule]
actions = []
author = ["me"]
description = "First rule to test some stuff"
enabled = false
exceptions_list = []
false_positives = []
filters = []
from = "now-360s"
index = ["apm-*-transaction*", "auditbeat-*", "filebeat-*", "logs-*", "winlogbeat-*"]
interval = "5m"
language = "eql"
license = ""
max_signals = 100
name = "Test Marc-Antoine"
note = "My investigation"
references = []
related_integrations = []
required_fields = []
risk_score = 21
risk_score_mapping = []
rule_id = "30e9fdac-e5ae-48e3-ae48-724c36198cf6"
setup = "My Setup"
severity = "low"
severity_mapping = []
tags = ["bruteforce"]
to = "now"
type = "eql"

query = '''
sequence by user.name
      	[authentication where event.action == "login-success"]
      	[authentication where event.action == "login-failed"]
      	until [authentication where event.action == "account-locked"]
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1110"
name = "Brute Force"
reference = "https://attack.mitre.org/techniques/T1110/"
subtechnique = []


[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

[rule.investigation_fields]
field_names = ["client.geo.country_name"]

[rule.meta]
from = "1m"
kibana_siem_app_url = "https://dac.kb.eu-west-3.aws.elastic-cloud.com/app/security"

