[metadata]
creation_date = "2025/03/25"
integration = []
maturity = "development"
updated_date = "2025/03/25"

[rule]
actions = []
author = ["me"]
description = "This rule lets me showcase detection as code with a bruteforce attempt"
enabled = false
exceptions_list = []
false_positives = []
filters = []
from = "now-360s"
index = [
    "apm-*-transaction*",
    "auditbeat-*",
    "endgame-*",
    "filebeat-*",
    "logs-*",
    "packetbeat-*",
    "traces-apm*",
    "winlogbeat-*",
    "-*elastic-cloud-logs-*",
]
interval = "5m"
language = "eql"
license = "orange"
max_signals = 100
name = "Demo DaC"
note = """# Title

This is where we investigate """
references = ["https://www.google.fr"]
related_integrations = []
required_fields = []
risk_score = 50
risk_score_mapping = []
rule_id = "e49493d6-66e3-4617-a3dd-73a38cd18ed9"
setup = """# Title
This is where setup happens"""
severity = "medium"
severity_mapping = []
tags = ["bruteforce", "windows"]
to = "now"
type = "eql"

query = '''
sequence by user.name
      	[authentication where event.action == "login-success"]
      	[authentication where event.action == "login-failed"]
      	until [authentication where event.action == "account-locked"]
'''


[[rule.threat]]
framework = "MITRE ATT&CK"
[[rule.threat.technique]]
id = "T1110"
name = "Brute Force"
reference = "https://attack.mitre.org/techniques/T1110/"
[[rule.threat.technique.subtechnique]]
id = "T1110.001"
name = "Password Guessing"
reference = "https://attack.mitre.org/techniques/T1110/001/"



[rule.threat.tactic]
id = "TA0006"
name = "Credential Access"
reference = "https://attack.mitre.org/tactics/TA0006/"

[rule.investigation_fields]
field_names = ["client.nat.port"]

[rule.meta]
from = "1m"
kibana_siem_app_url = "https://dac.kb.eu-west-3.aws.elastic-cloud.com/app/security"

